// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"wiretest/account"
	"wiretest/provider"
)

// Injectors from wire.go:

func InitializeAccountGenerator() account.AccountGenerator {
	accountNumberGeneratorConfig := provider.ProvideAccountNumberGeneratorConfig()
	generator := provider.ProvideAccountNumberGenerator(accountNumberGeneratorConfig)
	accountGenerator := provider.ProvideAccountGenerator(generator)
	return accountGenerator
}

func InitializeStubbedAccountGenerator() account.AccountGenerator {
	generator := provider.ProvideMockAccountNumberGenerator()
	accountGenerator := provider.ProvideAccountGenerator(generator)
	return accountGenerator
}
