// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"wiretest/account"
	"wiretest/provider"
)

// Injectors from wire.go:

func InitializeAccountGenerator() (account.AccountGenerator, error) {
	accountNumberGeneratorConfig := provider.ProvideAccountNumberGeneratorConfig()
	generator := provider.ProvideAccountNumberGenerator(accountNumberGeneratorConfig)
	accountGenerator := provider.ProvideAccountGenerator(generator)
	return accountGenerator, nil
}
